[[language]]
name = "latex"
file-types = ["tex", "sty", "cls"]
auto-format = false
language-servers = [ "texlab", { name = "ltex-ls", only-features = [ "code-action", "diagnostics" ] } ] 
indent = { tab-width = 4, unit = "    " }

[language-server.texlab]
config = { auxDirectory = "build" }

[language-server.texlab.build]
onSave = true

executable = "latexmk"
args = [
 "-pdflatex=lualatex",
 "-pdf",
 "-interaction=nonstopmode",
 "-synctex=1",
 "-file-line-error",
 "-output-directory=build",
 "%f"
 ]

[language-server.texlab.forwardSearch]
executable = "/Applications/Skim.app/Contents/SharedSupport/displayline" 
args = ["%l", "%p", "%f"]

[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = [ "ltex-ls" ]
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []

[[language]]
name = "xml"
file-types = ["xml", "gpx"]
